# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebe58bb00032dfaf69598c0f6949402dfa6068676fe3ff2e928ab82c21ff5e9192af5302596a22d395ce4ef7c47ed2553bb010b71674a7aab34c9300bd9fdbca

test:
  secret_key_base: 5cad16d99191e5e0be1f8a8d720b6b44ec02acfc1d767c0a942aa492f74fc62d2e29f82bb268c7a657613b40f374e07e5576ac11f7277fde211225aec7fc693a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
